### ISSUE TITLE
sctipt fails to run

### ISSUE THREAD

**Issue by Spudd86** [fin-ger/logitech-m720-config#10]
Starting the script after installing it, it immediately crashes

```

**Comment by fin-ger** [comment]
Looks like the mouse is not connected or not a M720 Triathlon. I added a report of currently connected devices to the beginning of the script, so you can check.

**Comment by Spudd86** [comment]
I had it connected over bluetooth, not the dongle. Is that why?

**Comment by tinnamchoi** [comment]
I seem to be having the same problem. I'm also using Bluetooth to connect rather than the Unifying dongle. 

```
### CURRENTLY CONNECTED DEVICES ###
     path     vendor_id product_id serial release manufacturer product interface driver               bus_id isDevice
Report Descriptor not processed for BID 0018 VID 000004F3 PID 000030FD: Expecting 4 usages but got 2

Report Descriptor not processed for BID 0018 VID 000004F3 PID 000030FD: Expecting 4 usages but got 2
Traceback (most recent call last):
  File "/home/tmt/.local/bin/m720-config", line 8, in <module>
    sys.exit(main())
  File "/path/to/logitech-m720-config/m720_config/__init__.py", line 156, in main
    buttons = SpecialKeysMseButtons ()
  File "/path/to/logitech-m720-config/m720_config/__init__.py", line 33, in __init__
    device_info = next (r for r in receivers () if r.product_id.lower() == "c52b")
StopIteration
```

**Comment by lingium** [comment]
> 我通过蓝牙连接它，而不是适配器。是因为这个吗？

yes, you have to change it to usb
