### ISSUE TITLE
AssertionErrorS

### ISSUE THREAD

**Issue by Amathadius** [fin-ger/logitech-m720-config#3]
m720-config
```
timeout (1.80/1.80) on device 255 request {83B5} params [03]
open DeviceInfo(path='/dev/hidraw6', vendor_id='046d', product_id='c52b', serial='', release=b'1208', manufacturer=b'Logitech', product=b'USB Receiver', interface=2, driver='hid-generic')
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/logitech_receiver/receiver.py", line 531, in open
    return Receiver(handle, device_info)
  File "/usr/lib/python3.7/site-packages/logitech_receiver/receiver.py", line 341, in __init__
    assert serial_reply
AssertionError
Exception ignored in: <function Receiver.__del__ at 0x7f7d1613d200>
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/logitech_receiver/receiver.py", line 370, in __del__
    self.close()
  File "/usr/lib/python3.7/site-packages/logitech_receiver/receiver.py", line 366, in close
    self._devices.clear()
AttributeError: 'Receiver' object has no attribute '_devices'
Traceback (most recent call last):
  File "/home/mathieu/.local/bin/m720-config", line 11, in <module>
    load_entry_point('m720-config', 'console_scripts', 'm720-config')()
  File "/home/mathieu/Git/logitech-m720-config/m720_config/__init__.py", line 148, in main
    buttons = SpecialKeysMseButtons ()
  File "/home/mathieu/Git/logitech-m720-config/m720_config/__init__.py", line 29, in __init__
    assert self.receiver
AssertionError
```

**Comment by fin-ger** [comment]
The `DeviceInfo` looks slightly different on my machine:

```
DeviceInfo(path='/dev/hidraw0', vendor_id='046d', product_id='c52b', serial='', release=b'2401', manufacturer=b'Logitech', product=b'USB Receiver', interface=2, driver='logitech-djreceiver')
```

I have a `logitech-djreceiver` driver. Do you know how to get this driver running on your distribution?

Another cause for this problem: Which python version are you using?

**Comment by fin-ger** [comment]
Please reopen if the issue persists
