### ISSUE TITLE
Won't run even connected with logitech receiver. 

### ISSUE THREAD

**Issue by eliocamp** [fin-ger/logitech-m720-config#6]
I'm getting the same error as #4, but my mouse is connected via the receiver and using Solaar. 

```
Traceback (most recent call last):
  File "/home/elio/.local/bin/m720-config", line 33, in <module>
    sys.exit(load_entry_point('m720-config', 'console_scripts', 'm720-config')())
  File "/home/elio/Downloads/logitech-m720-config/m720_config/__init__.py", line 149, in main
    buttons = SpecialKeysMseButtons ()
  File "/home/elio/Downloads/logitech-m720-config/m720_config/__init__.py", line 25, in __init__
    device_info = next (r for r in receivers () if r.product_id == "c52b")
StopIteration
```

I'm on elementary OS 5, based on Ubuntu 18.04.

**Comment by fin-ger** [comment]
Indeed, I can confirm this on Fedora.

I have a lot of other stuff on the table right now, so I won't have time to solve this in the near future, sry.
